name: CI
on:
  push:
    branches:
      - rawhide
  pull_request:
    branches:
      - rawhide

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:latest
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build fedpkg
        run: sudo dnf -y install fedpkg
      - name: Download source
        run: spectool -g libcerf.spec
      - name: Make SRPM
        run:  fedpkg srpm
      - name: Build rpm
        run: fedpkg mockbuild --mock-config /etc/mock/fedora-rawhide-s390x.cfg
