name: CI
on:
  push:
    branches:
      - rawhide
  pull_request:
    branches:
      - rawhide

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true 

jobs:
  CI:
    continue-on-error: true
    strategy:
      matrix:
        arch: ['i386', 'x86_64', 'aarch64', 'ppc64le', 's390x']
    runs-on: ${{ matrix.config.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    container:
      image: registry.fedoraproject.org/fedora:rawhide
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install fedpkg
        run: dnf -y install fedpkg
      - name: Download source
        run: spectool -g *.spec
      - name: Build rpm
        run: fedpkg mockbuild --mock-config /etc/mock/fedora-rawhide-${{ matrix.arch }}.cfg -- --isolation=simple
